### ISSUE TITLE
Discontinuous roads - why?

### ISSUE THREAD

**Issue by goldfndr** [twpol/osm-tiles#1]
If I zoom in [on Luton](https://osm-tiles.james-ross.co.uk/?map=16/51.879067/-0.420388), I get a weird effect, with what look like roads being discontinuous at nodes. Also, part (toward city center) is unrendered; too much data?

**Comment by twpol** [comment]
I made an embarrassing mistake in the scaling function (radians vs degrees) so the calculation for how wide the road should be for a particular zoom is just going crazy in many places. Fix is nearly ready.

**Comment by twpol** [comment]
All fixed on the slippy map. Thanks for spotting! :)
