### ISSUE TITLE
Add project to taginfo projects list

### ISSUE THREAD

**Issue by twpol** [twpol/osm-tiles#2]
As a project which uses OpenStreetMap tags, we should have it listed on https://taginfo.openstreetmap.org/projects. To do that, we need:

- Add a `taginfo.json` file in the respository (https://wiki.openstreetmap.org/wiki/Taginfo/Projects)
- Add to project list at https://github.com/taginfo/taginfo-projects/blob/master/project_list.txt (https://github.com/taginfo/taginfo-projects/blob/master/CONTRIBUTING.md)

**Comment by twpol** [comment]
In progress over in https://github.com/taginfo/taginfo-projects/pull/57

**Comment by goldfndr** [comment]
It's now available.
