### ISSUE TITLE
Two-way highway=service/track/path should default to 1 lane

### ISSUE THREAD

**Issue by twpol** [twpol/osm-tiles#20]
Per the assumptions on the wiki at https://wiki.openstreetmap.org/wiki/Key:lanes#Assumptions the three tags `highway=service =track =path` should default to 1 lane in two-way cases.

**Comment by goldfndr** [comment]
Any plans to add track or path or steps or footway or cycleway or bridleway?

**Comment by twpol** [comment]
Hadn't originally planned for any of those, but at least standalone cycleways would make sense to connect to the roads. The others less so, but track could be a 1 lane road with a different colour?
