### ISSUE TITLE
Visualize oneway arrows

### ISSUE THREAD

**Issue by voschix** [twpol/osm-tiles#23]
In the present demo site the one-way arrows are not visible. They are important to decide whether a road is single-lane one-way or single-lane two-way (or no no lane-number tagging)
(I have just visited the demo site for the first time - I may have missed something)

**Comment by goldfndr** [comment]
Currently, the oneway tag is only used to help decide the count of lanes if the lanes tag is not present. One-way directionality is not implemented, [but it is planned](https://github.com/twpol/osm-tiles/pull/6#issuecomment-412330651).
